### ISSUE TITLE
wordlists

### ISSUE THREAD

**Issue by hakxcore** [trickest/mkpath#4]
#### Issues in this epic:

- [ ] Please provide the path to wordlists or add one to the repository

**Comment by mhmdiaa** [comment]
Hey @hakxcore, mkpath is meant to be a flexible tool that can work with any wordlist (preferably a wordlist that's created custom for a particular target) so we won't be adding any wordlists to this repository.

Here are some repositories that you might find interesting though:
- https://github.com/danielmiessler/SecLists
- https://github.com/six2dez/OneListForAll
- https://github.com/digininja/CeWL

**Comment by hakxcore** [comment]
Thankyou so much @mhmdiaa  for clarifying.
